### PR TITLE
Upgrade flux resources to v1in weave-policy-agent

### PR DESCRIPTION
**Pull request by serboctor**
This PR upgrades charts that create Kustomization and GitRepository `v1beta2` CRs to `v1` CRs and bumps the agent profile to policy-agent 2.4.0.

### CODE REVIEW

**Review by waleedhammam — DISMISSED** [review]

**Comment by steve-fraser** [comment]
Please don't merge these. We have not upgraded all clusters

**Comment by steve-fraser** [comment]
@darrylweaver please review this ^

**Review by darrylweaver — COMMENTED** [review]
This is for Flux 2 GA when it is released and after Weave Gitops Enterprise has released a version that works with Flux 2 and we have coordinated all the upgrades in the demo environments.  So, this cannot be merged until all of that is completed or it would break existing demos.

**Comment by serboctor** [comment]
> This is for Flux 2 GA when it is released and after Weave Gitops Enterprise has released a version that works with Flux 2 and we have coordinated all the upgrades in the demo environments. So, this cannot be merged until all of that is completed or it would break existing demos.

@darrylweaver since WGE has been released with support for Flux GA last week, is it safe to merge this now? or are the demo environment still outdated? Also, does the same apply for [this](https://github.com/weaveworks/profiles-catalog/pull/212) PR.

**Review by waleedhammam — APPROVED** [review]

**Pull request merged**
